/*-- 创建表imgInfo */
create table imgInfo
(
  id  NUMBER(10) PRIMARY KEY,
  userName      VARCHAR2(50),
  cardInfo  VARCHAR2(30),
  imgBase CLOB,
  statu   CHAR(1),
  creatTime DATE ,
  updateTime  DATE
)
COMMENT ON TABLE IMGINFO IS '用户人像信息表';
COMMENT ON COLUMN IMGINFO.ID IS '序列号ID';
COMMENT ON COLUMN IMGINFO.USERNAME IS '用户账号';
COMMENT ON COLUMN IMGINFO.CARDINFO IS '用户身份证号码';
COMMENT ON COLUMN IMGINFO.IMGBASE IS '用户人像BASE64信息大字段';
COMMENT ON COLUMN IMGINFO.STATU IS '用户信息状态：0-失效 1-有效';
COMMENT ON COLUMN IMGINFO.CREATTIME IS '创建时间';
COMMENT ON COLUMN IMGINFO.UPDATETIME IS '更新时间';

create index INDEX_USERNAME on IMGINFO (USERNAME);

CREATE SEQUENCE seq_imgInfo
START WITH 1
INCREMENT BY 1
/*-- 创建表imgInfo end. */